#!/usr/bin/env ruby
# vim: syntax=ruby ts=2 sts=2 expandtab
#

require 'rubygems'
require 'json'
require 'jsonpath'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end
  opts.on("-e", "--expression json.expr", "json path expr") do |v|
    options[:expression] = v
  end
end.parse!

=begin
class Object
  def method_missing(sym,*args)
    if args.empty? && respond_to?("[]")
      if (respond_to(:key?) && key?(sym)) || is_a?(Array)
        return self[sym]
      end
    end
    super(sym, *args)
  end
end
=end
ARGF.each do |line|
  json = JSON.parse(line)
  puts JSONPath.lookup(hash_or_array, options[:expression])
end

